---
title: Geluidsniveau meter
hero_image: images/banner.png
description: Meet, toon en log geluidsniveaus op je micro:bit! Stel een alarm in als het niveau te hoog is.
version: 4
listed: true
copyedit: true
last_tested: '2023-08-15'
steps:
  - title: Wat ga je maken
  - title: Niveau meter
    completion:
      - engaged
  - title: Sla alarm!
  - title: Wijzig de gevoeligheid
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Wat kun je verder nog doen?
