---
title: Sound level meter
hero_image: images/banner.png
description: 
  Measure, display, and log sound levels on your micro:bit! Set an alarm if the level is too high.
version: 4
listed: true
copyedit: true
last_tested: '2023-08-15'
steps:
- title: You will make
- title: Level meter
  completion:
    - engaged
- title: Sound the alarm!
- title: Change the sensitivity
  completion:
    - internal
- title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
      - external
- title: Upgrade your project
- title: What next?
